[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[edge_functions]]
  pattern = "/download*"
  function = "download-redirect"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
